mandatory:
    Blueprint:
        blueprint_name:   &blueprint_name   'dev056-mp3s-crk-lon-mp-c2'
        vSphere_id:       &vSphere_id       'vSphere_Machine_1'
################################# Configuration section #############################################################
onboard_cluster_type: MP3S

blueprints:
  - *blueprint_name

blueprint_machine_pairs:
    {*blueprint_name: *vSphere_id}

deploy_vm:
    with_dp: False
    description: 'deploy vm'
    number_of_vm: 1
    backup_service_level:
    SRM_power_on_priority:
    reason_for_request: test WF

deployed_vms:

operate_vm:
    basic_action_list:
        - 'Power On'
        - 'Power Off'
        - 'Reboot'

