# ################################ Configuration section #############################################################
# Automation user only needs to update the parameters in this section
# [Mandatory] parameters : you must update with the right ones in your environment.
# [Optional] parameters : you can suggested to update with your own, but not mandatory.
mandatory:
  Cluster:
    # CA1S Cluster name
    cluster_name:              &cluster_name             'DK-GZ-CA2S-C2'
  Vcenter:
    vCenter_fqdn:              &vcenter_fqdn             'vcs01.vlab.local'
    # Datacenter name in vCenter you configure
    vCenter_datacenter:                &datacenter               'Dakar'
  Reservation:
    # Computer resource (Cluster) you want to configure in reservation
    computer_resource:         &computer_resource        'CRK-LON-CA-C1 (vcs01)'
    memory_in_GB:              &mem                      2
    storage_size_in_GB:        &res_storage_size         32
    # Network path you want to configure in reservation
    network_path:              &network_path             'vxw-dvs-101-virtualwire-21-sid-10005-LS_CRK-LON-CA-C1'
  ViPR:
    # vArray in ViPR, the vArray must has physical connection to the vCenter you configure above
    vipr_varray_A:               &vipr_varray01          'DK-HWI-1-vArray1'
    vipr_varray_B:               &vipr_varray02          'GZ-HWI-1-vArray1'
  provision_cloud_storage:
    1-storage_tier:             &vipr_storage_tier         'CRK-XIO-Local; available'
    2-storage_type:             &storage_type               'VMFS'
    3-size_in_GB:               &provision_size             30
  Virtual machine blueprint:
    # Blueprint name you configure in the automation environment
    blueprint_name:            &blueprint_name            'Blueprint'
    # virtual machine name you configure in the automation environment
    vSphere_Machine_ID:      &vSphere_Machine_ID                        'vSphere_Machine_1'


################################# Configuration section #############################################################
# no need to write
optional:
    site_name01:              &site_name01               'CA2S-site01'
    site_name02:               &site_name02              'CA2S-site02'
    vcenter_name:              &vcenter_name             'CA2S-vCenter01'
    new_site_name:             &new_site_name            'CA2S-site01-new'
    new_vcenter_name:          &new_vcenter_name         'CA2S-vCenter01-new'
    hardware_islands:
      hwi_name01:           &hwi_name01         'CA2S-HWI-1'
      hwi_name02:           &hwi_name02         'CA2S-HWI-2'
      new_hwiname:          &edit_hwi_name       CA2S-HWI-1-new
    cluster_type:              &cluster_type             'CA2S'
    reasons: &reasons 'deploy CA2S cluster'
    reservation_data:
      reservation_name:   &reservation_name         'E2E_Res_CA2S'
      network_profile:    &network_profile          'unknown'
    reservation_policy_name:   &reservation_policy_name  'E2E_Res_Policy_CA2S'
keys_to_constants:
      storage_typea:        &storage_type_a     BLOCK
      storage_typeb:        &storage_type_b     VSAN
      inter_site_vs_intra_site:  &inter_vs_intra           'Inter-site'
Intermediate_keys:
      added_site: &added_site []
      added_vcenter: &added_vcenter []
      added_hwi: &added_hwi []
      existed_clusters: &existed_clusters []
      added_reservation_name: &added_reservation_name []
      added_reservation_policy_name: &added_reservation_policy_name []
      assigned_buleprint: &assigned_buleprint []
      assigned_reservation: &assigned_reservation []
      datastorage_name: &datastorage_name []

#################################################################################################################
# no need to write
onboard_cluster_type: *cluster_type

blueprints:
    - *blueprint_name
blueprint_machine_pairs:
   {*blueprint_name: *vSphere_Machine_ID}

deploy_vm:
    with_dp: False
    description: deployvm
    number_of_vm: 1
    backup_service_level:
    SRM_power_on_priority:
    reason_for_request: test

deployed_vms:
 []

existed_clusters:
  - *cluster_name

add_sites:
    - *site_name01
    - *site_name02

added_sites:
   - *site_name01
   - *site_name02

edit_sites:
    - site_name: *site_name01
      new_site_name: *new_site_name

add_vcenter:
    -
      select_operation: Add vCenter
      name_for_vcenter_endpoint: *vcenter_name
      select_vc_fqdn_to_add: *vcenter_fqdn
      new_vcenter_associated_sites:
                                  - *site_name01
                                  - *site_name02
      select_datacenter_to_add: *datacenter

added_vcenter:
  - *vcenter_name

update_vcenter:
  -
    select_operation: Edit vCenter
    existing_vcenter_object: *vcenter_name
    vcenter_name: *new_vcenter_name
    vcenter_fqdn: *vcenter_fqdn
    datacenter: *datacenter
    sites:
        - *site_name01
    vcenter_username: administrator@vsphere.local
    vcenter_password: Password123!

delete_vcenter:
    select_operation: Delete vCenter
    select_vcenter:
    ensure_delete_info: Confirm

add_hwi:
   -
      hwi_name: *hwi_name01
      performed_active: Add VxRack(Flex)/VxBlock based Hardware Island
      vcenter_name_active: *vcenter_name
      site_name_active: *site_name01
      storage_type: *storage_type_a
      vipr_active: ViPR
      vipr_active_check: [*vipr_varray01]
   -
      hwi_name: *hwi_name02
      performed_active: Add VxRack(Flex)/VxBlock based Hardware Island
      vcenter_name_active: *vcenter_name
      site_name_active: *site_name02
      storage_type: *storage_type_a
      vipr_active: ViPR
      vipr_active_check: [*vipr_varray02]

added_hwi:
  - *hwi_name01
  - *hwi_name02

update_hwi:
    -
      old_hwi_name: *hwi_name01
      edit_hwi_name: *edit_hwi_name
      performed_active: Edit VxRack(Flex)/VxBlock based Hardware Island
      edit_vcenter_name_active: *vcenter_name
      edit_site_name_active: *site_name01
      vipr_active: ViPR
      vipr_active_check:
              - *vipr_varray01

onboard_ca_cluster:
   select_hardward_island_1: *hwi_name01
   select_unprepared_cluster: *cluster_name
   choose_inter_site_vs_intra_site: *inter_vs_intra
   select_hardward_island_2: *hwi_name02
   select_hosts_for_hardware_island_1:
   select_hosts_for_hardware_island_2:

operate_vm:
    basic_action_list:
      - Power On
      - Power Off
      - Reboot
    user_action_list:
      - Power Off

delete_cluster:
    []

provision_cloud_storage:
    - 'description': 'Provision Cloud Storage'
      'reasons': 'pcs'
      'storage_type': *storage_type
      'vipr_storage_tier': *vipr_storage_tier
      'size_in_gb': *provision_size
      'request': 'unknown'
      'hwi_name': *hwi_name01

added_cloud_storage:
    -
      hwi_name: *hwi_name01
      cluster_name: *cluster_name
      name:
        ['Site-A-HA-Pool_1476339694076']
      srp: []

create_reservation_policy:
    names: [*reservation_policy_name]

create_reservation:
  -
    reservation_name: *reservation_name
    reservation_type: vSphere
    reservation_priority: 1
    computer_resource: *computer_resource
    memory: *mem
    storage_size: *res_storage_size
    storage_priority: 1
    network_path: *network_path
    network_profile: *network_profile

added_reservation_policy:
  [*reservation_policy_name]

added_reservation:
  [*reservation_name]

assigned_reservation_policy_reservations:
- *reservation_name

assigned_reservation_policy_blueprints:
- *blueprint_name

assign_reservation_policy_to_reservation:
    reservation_names: [*reservation_name]
    reservation_policy_names: [*reservation_policy_name]

assign_reservation_policy_to_blueprint:
    blueprint_names: []
    reservation_policy_name: *reservation_policy_name

delete_datastore:
    - description: Delete Logic
      reasons: del logic
      request: unknown

edit_cluster_hwi:
    - cluster: *cluster_name
      hwi_1: *hwi_name01
      hwi_2: *hwi_name02


delete_hwi:
    del_reasons: tear down
    del_description: delete hwi
    del_performed_active: Delete Hardware Island
    isdel_obj: Confirm

delete_sites:
    description: deletesite
    action_to_be_performed: Delete Site
    please_pick_a_site_to_delete:
    please_confirm_that_you_wish_to_delete_this_site: Confirm