# ################################ Configuration section #############################################################
# Automation user only needs to update the parameters in this section
# [Mandatory] parameters : you must update with the right ones in your environment.
# [Optional] parameters : you can suggested to update with your own, but not mandatory.

mandatory:
    vCenter:
        vCenter_fqdn:              &vcenter_fqdn             'vcs01.vlab.local'
        vCenter_datacenter:                &datacenter               'Dakar'
    Cluster:
        cluster_name:              &cluster_name              'DRK-HWI-1-C1'
    Avamar grid:
        1-avamar_grid_fqdn:     &avamar_grid_fqdn_name     'qe-avp01.vlab.local'
        2-admin_user_name:           &admin_user_name           'root'
        3-admin_password:            &admin_password            'Password123!'
        4-soap_user_name:            &soap_user_name            'MCUser'
        5-soap_password:             &soap_password             'Password123'
    ViPR:
        vipr_varray:               &vipr_varray               'DK-HWI-1-vArray1'
    provision_cloud_storage:
        1-storage_tier:             &vipr_storage_tier         'CRK-XIO-Local; available'
        2-storage_type:             &storage_type               'VMFS'
        3-size_in_GB:               &provision_size             30
    Reservation:
        1-computer_resource:         &computer_resource         'CRK-HWI-1-C1'
        2-memory_in_GB:              &memory                     20
        3-storage_size_in_GB:        &storage_size               20
        4-network_path:              &network_path              'vxw-dvs-101-virtualwire-18-sid-10002-LS_CRK-HWI-1-C1'
    Backup Service Level:
        additional_email:            &additional_email        'benson.xiong@emc.com'
    Virtual machine blueprint:
        blueprint_name:             &blueprint_name            'dev123_CA1S'
        vSphere_Machine_ID:         &vSphere_Machine_ID        'vSphere_Machine_1'

optional:
    site_name:                  &site_name                 'LC1S-DP-Site'
    new_site_name:              &new_site_name             'LC1S-DP-Site-new'
    vcenter_name:               &vcenter_name              'LC1S-DP-vcs01'
    new_vcenter_name:           &new_vcenter_name          'LC1S-DP-vcs01-new'
    hwi_name:                   &hwi_name                  'LC1S-DP-HWI-1'
    new_hwi_name:               &new_hwi_name              'LC1S-DP-HWI-1-new'
    avamar_grid_name:           &avamar_grid_name          'LC1S-DP-Avamar-Grid010'
    new_avamar_grid_name:       &new_avamar_grid_name      'LC1S-DP-Avamar-Grid01-new'
    reservation_name:           &reservation_name          'LC1S-DP-R'
    reservation_policy_name:    &reservation_policy_name   'LC1S-DP-RP'
    Backup Service Level:
        backup_service_level_name:  &backup_service_level_name 'operate-vm-backup-svc-LC1S-DP'
        set_backup_service_level_name: &set_backup_service_level_name 'set-backup-svc-LC1S-DP'
################################# Configuration section #############################################################
#contants
Keys_to_contants:
    onboard_cluster_type:   &cluster_type   'LC1S'
#variable to make debug easier
Intermediate_keys:
    added_sites: &added_sites []
    added_vcenter: &added_vcenter []
    added_hwi: &added_hwi []
    existed_clusters: &existed_clusters []
    added_reservation_name: &added_reservation_name []
    added_reservation_policy_name: &added_reservation_policy_name []
    assigned_buleprint: &assigned_buleprint []
    assigned_reservation: &assigned_reservation []
    added_avamar_grid: &added_avamar_grid []
    # added_avamar_site_relationship
    asr_name: &asr_name
    sites: &sites []
    backup_environment_type: &backup_environment_type   #'1C1VC'
    added_avamar_replication_relationship: &added_avamar_replication_relationship []
    # paramters to added_backup_service_level
    backup_to_operate_vm: &backup_to_operate_vm
    backup_to_set_backup_service: &backup_to_set_backup_service
    datastorage_name: &datastorage_name []
    storage_hwi: &storage_hwi
    storage_cluster: &storage_cluster
    srp: &srp []
    deployed_vms: &deployed_vms []

onboard_cluster_type: *cluster_type

blueprints:
    - *blueprint_name

blueprint_machine_pairs:
    {*blueprint_name: *vSphere_Machine_ID}

add_sites:
    - *site_name

edit_sites:
    - site_name: *site_name
      new_site_name: *new_site_name

add_vcenter:
    - 'select_operation': 'Add vCenter'
      'name_for_vcenter_endpoint': *vcenter_name
      'select_vc_fqdn_to_add': *vcenter_fqdn
      'new_vcenter_associated_sites': [*site_name]
      'select_datacenter_to_add': *datacenter

update_vcenter:
    - 'select_operation': Edit vCenter
      'existing_vcenter_object': *vcenter_name
      'vcenter_name': *new_vcenter_name
      'vcenter_fqdn': *vcenter_fqdn
      'datacenter': *datacenter
      'sites': [*site_name]
      vcenter_username: administrator@vsphere.local
      vcenter_password: Password123!

add_hwi:
  -
    hwi_name: *hwi_name
    performed_active: Add VxRack(Flex)/VxBlock based Hardware Island
    vcenter_name_active:  *vcenter_name
    site_name_active: *site_name
    storage_type: 'BLOCK'
    vipr_active: ViPR
    vipr_active_check:
      - *vipr_varray
    request: unknown

update_hwi:
  -
    performed_active: Edit VxRack(Flex)/VxBlock based Hardware Island
    old_hwi_name: *hwi_name
    edit_hwi_name: *new_hwi_name
    edit_vcenter_name_active: *vcenter_name
    edit_site_name_active: *site_name
    vipr_active: ViPR
    vipr_active_check:
      - *vipr_varray

onboard_local_cluster:
    'select_a_hardware_island':
    'select_unprepared_cluster': *cluster_name

add_avamar_grid:
    - description: add avamargrid01
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *avamar_grid_name
      avamar_grid_fqdn_name: *avamar_grid_fqdn_name
      admin_user_name: *admin_user_name
      admin_password: *admin_password
      soap_user_name: *soap_user_name
      soap_password: *soap_password
      request: unknown
      site_name: *site_name

delete_avamar_grid:
    description: delete_avamar_grid
    select_operation_type: Delete Avamar Grid
    confirmation: Confirm

edit_admin_full:
    - description: update avamargrid01
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: *new_avamar_grid_name
      email_notification: Confirm
      admin_full: True

edit_avamar_grid:
    - description: update avamargrid01
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: *avamar_grid_name
      new_avamar_grid_name: *new_avamar_grid_name
      edit_avamar_grid_fqdn_name: *avamar_grid_fqdn_name
      edit_admin_user_name: *admin_user_name
      edit_admin_password: *admin_password
      edit_soap_user_name: *soap_user_name
      edit_soap_password: *soap_password
      edit_site_name: *site_name
      email_notification: Confirm
      request: unknown

add_avamar_site_relationship:
  backup_env_type: 1C1VC
  site_first: *site_name
  site_second:
  site_third:

edit_avamar_site_relationship:
  site_first: *site_name
  site_second: ''
  site_third: ''

add_an_avamar_replication_relationship:
  -
    allow_duplicated_arr: False
    description: 'add arr'
    avamar_site_relationship_name:
    site1_avamar_grid:
    site2_avamar_grid:
    site3_avamar_grid:

edit_avamar_replication_relationship:
    # Keep this key empty, it will fetch added arr
    'arr':
    'admin_full': Yes

cluster_asr_to_associate:
    description: associate cluster to ASR
    reasons: testing
    cluster_action: Associate Cluster to ASR

associated_cluster_asr:
    []

avamar_proxies_cluster_to_associate:
    -  avamar_proxies: []

associated_avamar_proxy_cluster:
    []

add_backup_service_level:
    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *backup_service_level_name
      'select_backup_schedule': 'Monthly'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'Until'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Daily'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *set_backup_service_level_name
      'select_backup_schedule': 'Daily'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'For'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Monthly'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

provision_cloud_storage:
    - 'description': 'Provision Cloud Storage'
      'reasons': 'pcs'
      'storage_type': *storage_type
      'vipr_storage_tier': *vipr_storage_tier
      'size_in_gb': *provision_size
      'request': 'unknown'
      'hwi_name': *hwi_name

edit_cluster_site:
    - cluster: *cluster_name
      site: *site_name
      hwi: *hwi_name

edit_cluster_hwi:
    - cluster: *cluster_name
      hwi_1: *hwi_name
      hwi_2:

create_reservation_policy:
    names:
      - *reservation_policy_name

create_reservation:
  -
    reservation_name: *reservation_name
    reservation_type: vSphere
    reservation_priority: 1
    computer_resource: *computer_resource
    memory: *memory
    storage_size: *storage_size
    storage_priority: 1
    network_path: *network_path
    network_profile: unknown

assign_reservation_policy_to_reservation:
    reservation_names: []
    reservation_policy_names: []

assign_reservation_policy_to_blueprint:
    blueprint_names: []
    reservation_policy_name:

deploy_vm:
    with_dp: True
    description: ''
    number_of_vm: 1
    backup_service_level: 'set-operate-vm-backup-svc-LC1S-DP-014141'
    SRM_power_on_priority:
    reason_for_request: test WF

operate_vm:
    basic_action_list:
        - 'Power On'
        - 'Power Off'
        - 'Reboot'
    user_action_list:
        - 'Power Off'

set_backup_service_level:
    backup_service_level_name:

display_backup_service_level:
    please_select_action_for_backup_service_level: Display Backup Service Levels
    additional_email: *additional_email
    email: Confirm

on_demand_backup_vm:
    vm_name:
    description: A description of on_demand_backup_vm
    reasons: A reason of on_demand_backup_vm

delete_backup_service_level:
    - 'description': 'delete_backup_service_level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Delete Backup Service Level'
      'select_backup_service_level_to_delete':
      'confirm_deletion_of_backup_service_level': Yes

    - 'description': 'delete_backup_service_level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Delete Backup Service Level'
      'select_backup_service_level_to_delete':
      'confirm_deletion_of_backup_service_level': Yes

delete_datastore:
    - 'description': 'Delete Datastore'
      'reasons': 'tear down'

delete_cluster:
    []

delete_hwi:
    del_performed_active: Delete Hardware Island
    isdel_obj: Confirm

delete_vcenter:
    description: delete vcenter
    reasons: tear down
    select_operation: Delete vCenter
    ensure_delete_info: Confirm

delete_sites:
    'description': 'deletesite'
    'action_to_be_performed': 'Delete Site'
    'please_pick_a_site_to_delete':
    'please_confirm_that_you_wish_to_delete_this_site': 'Confirm'

run_admin_report:
    description: run admin report
    reasons: run reason
    select_a_backup_service_level_name:
    select_pdf_page_orientation: Portrait
    select_one_or_more_reports_to_run:
    select_a_time_frame: Last Day
    email_results: Yes
    email_address: 123@emc.com

delete_avamar_site_relationship:
  description: delete avamar site relationship demo
  action: Delete an ASR

deleted_avamar_site_relationship:
delete_avamar_grid:
    description: delete_avamar_grid
    select_operation_type: Delete Avamar Grid
    confirmation: Confirm

delete_avamar_replication_relationship:
    description: delete arr
    delete_arr:

delete_vcenter_relatinship:
    description: del_vcenter_relationship02
    reasons: delrelationship
    please_select_the_operation: Delete vCenter Relationship
    protected_vcenter:
    recovery_vcenter:

added_sites:
    *added_sites

added_vcenter:
    *added_vcenter

added_hwi:
    *added_hwi

existed_clusters:
    *existed_clusters

added_avamar_grid:
    *added_avamar_grid

added_avamar_site_relationship:
  -
    asr_name: *asr_name
    backup_env_type: *backup_environment_type
    sites: *sites


added_avamar_replication_relationship:
  *added_avamar_replication_relationship

added_backup_service_level:
  {
    'backup_to_operate_vm': *backup_to_operate_vm,
    'backup_to_set_backup_service': *backup_to_set_backup_service
  }

added_cloud_storage:
   - hwi_name: *storage_hwi
     cluster_name: *storage_cluster
     name: *datastorage_name
     srp: *srp

added_reservation_policy: *added_reservation_policy_name

added_reservation: *added_reservation_name

assigned_reservation_policy_reservations: *assigned_reservation

assigned_reservation_policy_blueprints: *assigned_buleprint

deployed_vms: *deployed_vms