mandatory:
    Blueprint:
        blueprint_name:                 &blueprint_name                   'dev056-blueprint'
        vsphere_blueprint_name:         &vsphere_blueprint_name           'vSphere_Machine_1'
    Backup Service Level:
        backup_service_level_1_name:    &backup_service_level_1_name      'operate-vm-backup-svc-MP3S-DP'
        backup_service_level_2_name:    &backup_service_level_2_name      'set-backup-svc-MP3S-DP'
################################# Configuration section #############################################################
blueprints:
    - *blueprint_name

blueprint_machine_pairs:
    {*blueprint_name: *vsphere_blueprint_name}

deploy_vm:
    description: 'deploy_vm'
    with_dp: True
    number_of_vm: 1
    backup_service_level: *backup_service_level_1_name
    SRM_power_on_priority:
    reason_for_request: 'test deploy_vm'

operate_vm:
    basic_action_list:
        - 'Power On'
        - 'Power Off'
        - 'Reboot'
    user_action_list:
        - 'Power Off'

added_backup_service_level:
  {
    backup_to_operate_vm: *backup_service_level_1_name,
    backup_to_set_backup_service: *backup_service_level_2_name
  }

run_admin_report:
    description: run admin report
    reasons: run reason
    select_a_backup_service_level_name:
    select_pdf_page_orientation: Portrait
    select_one_or_more_reports_to_run:
    select_a_time_frame: Last Day
    email_results: Yes
    email_address: 123@emc.com

display_backup_service_level:
    please_select_action_for_backup_service_level: Display Backup Service Levels
    email: Confirm
