#################################################################################################################
# Caveats:
#     Preconditions:
#         1. Sites are created;
#         2. vCenters are added;
#         3. Hardware Islands are created;
#         4. "Onboard DR Cluster" (DR2S) catalog request is submitted.
#################################################################################################################
mandatory:
    Avamar_grids_configurations:
       1-protected_avamar_grid_fqdn:             &grid_a_fqdn          'cork-ave02.vlab.local'
       2-recovery_avamar_grid_fqdn:              &grid_c_fqdn          'paris-ave01.vlab.local'
       3-protected_admin_username:   &ag_admin_user        'root'
       4-protected_admin_password:   &ag_admin_pwd         'Password123!'
       5-protected_soap_user:        &ag_soap_user         'root'
       6-protected_soap_password:    &ag_soap_pwd          'Emsee123_'
    Existing_sites:
       1-protected_site_name:           &site_a                 'SiteCork'
       2-recovery_site_name:          &site_c                 'SiteParis'
    Existing_vCenters:
       1-protected_vCenter_name:             &vcs01_name             'vcs01'
       2-protected_vCenter_fqdn:             &vcs01_fqdn             'vcs01'
       3-protected_vCenter_datacenter:       &vcs01_dc               'Cork'
       4-recovery_vCenter_name:              &vcs03_name             'vcs03'
       5-recovery_vCenter_fqdn:              &vcs03_fqdn             'vcs03'
       6-recovery_vCenter_datacenter:        &vcs03_dc               'Paris'
    Existing_hardware_islands:
       1-protected_HWI_name:            &hwi_a                  'DR2S-CRK-HWI-1'
       2-recovery_HWI_name:           &hwi_b                  'DR2S-PAR-HWI-1'
    Onboarded_cluster:
       1-protected_cluster_name:        &protected_cluster      'CRK-PAR-DR-C1'
       2-recovery_cluster_name:         &recovery_cluster       'PAR-CRK-DR-C1'
#################################################################################################################
optional_parameters:
    vRA:
        email:                &vra_email              admin@vlab.local
    avamar_grids:
        grid_4_protected_site:
            name:             &grid_a                 cork-ave01
        grid_4_recovery_site:
            name:             &grid_c                 paris-ave01
        grid_name_edit:       &grid_name_edit         cork-ave01-edit
    backup_servcie_level:
        name:                 &busl_name              backup-svc-E2E7-DR2S-DP
#################################################################################################################
added_sites:
  - *site_a
  - *site_c

added_vcenter:
  - *vcs01_name
  - *vcs03_name

added_hwi:
  - *hwi_a
  - *hwi_b

existed_clusters:
  - *protected_cluster
  - *recovery_cluster

#################################################################################################################
## For Debugging
#added_avamar_grid: [
#  *site_a,
#  *site_c
#]

#added_avamar_site_relationship:
# - asr_name:
#   backup_env_type:
#   sites: []

#  asr_name: ASR00014
#  backup_env_type: 2C2VC
#  sites: [*site_a, *site_b]

#added_avamar_replication_relationship: [
# ]

#added_backup_service_level:
#  backup_to_set_backup_service: *busl_name
#  backup_to_operate_vm: ''
#  backup_to_set_backup_service: ''

#associated_avamar_proxy_cluster: []
#################################################################################################################
### Nodes for running workflow
onboard_cluster_type: DR2S

add_avamar_grid:
    - description: add avamar grid01
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_a
      avamar_grid_fqdn_name: *grid_a_fqdn
      admin_user_name: *ag_admin_user
      admin_password: *ag_admin_pwd
      soap_user_name: *ag_soap_user
      soap_password: *ag_soap_pwd
      request: unknown
      site_name: *site_a

    - description: add avamar grid02
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_c
      avamar_grid_fqdn_name: *grid_c_fqdn
      admin_user_name: *ag_admin_user
      admin_password: *ag_admin_pwd
      soap_user_name: *ag_soap_user
      soap_password: *ag_soap_pwd
      request: unknown
      site_name: *site_c

get_asr_from_vro:
    available_asr: []

edit_admin_full:
    - description: edit_admin_full avamar grid01
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: *grid_name_edit
      email_notification: Confirm
      admin_full: True

edit_avamar_grid:
    - description: update avamar grid01
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: *grid_a
      new_avamar_grid_name: *grid_name_edit
      edit_avamar_grid_fqdn_name: *grid_a_fqdn
      edit_admin_user_name: *ag_admin_user
      edit_admin_password: *ag_admin_pwd
      edit_soap_user_name: *ag_soap_user
      edit_soap_password: *ag_soap_pwd
      request: unknown
      edit_site_name: *site_a
      email_notification: Confirm

edit_avamar_site_relationship:
  site_first: *site_a
  site_second: *site_c
  site_third: ''

edit_avamar_replication_relationship:
    # Keep this key empty, it will fetch added arr
    arr:
    admin_full: Yes

add_avamar_site_relationship:
  description: add avamar site relationship demo
  action: Add an ASR
  backup_env_type: 2C2VC
  site_first: *site_a
  site_second: *site_c

add_an_avamar_replication_relationship:
  -
    allow_duplicated_arr: False
    description: add arr
    operation_type: Add Avamar Replication Relationship
    avamar_site_relationship_name:
    site1_avamar_grid: *grid_a
    site2_avamar_grid: *grid_c
    site3_avamar_grid:

get_arr_from_vro:
    available_arr: []

cluster_asr_to_associate:
    description: associate cluster to ASR
    reasons: testing
    cluster_action: Associate Cluster to ASR

associated_cluster_asr: []

add_backup_service_level:
    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *busl_name
      'select_backup_schedule': 'Monthly'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'Until'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Daily'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

display_backup_service_level:
    please_select_action_for_backup_service_level: Display Backup Service Levels
    additional_email: *vra_email
    email: Confirm

avamar_proxies_cluster_to_associate:
    - avamar_proxies: []
    - avamar_proxies: []

run_admin_report:
  description: run admin report
  reasons: run reason
  select_a_backup_service_level_name: *busl_name
  select_pdf_page_orientation: Portrait
  select_one_or_more_reports_to_run:
  select_a_time_frame: Last Day
  email_results: Yes
  email_address: *vra_email

delete_backup_service_level:
  - description: delete_backup_service_level_operate_vm
    reasons: reasons
    please_select_action_for_backup_service_level: Delete Backup Service Level
    select_backup_service_level_to_delete:
    confirm_deletion_of_backup_service_level: Yes

delete_avamar_replication_relationship:
    description: delete arr
    operation_type: Delete Avamar Replication Relationship
    delete_arr: None

delete_avamar_site_relationship:
  description: delete avamar site relationship demo
  action: Delete an ASR

delete_avamar_grid:
    description: delete_avamar_grid
    select_operation_type: Delete Avamar Grid
    confirmation: Confirm