#################################################################################################################
# Caveats:
#     Preconditions:
#         1. Sites are created;
#         2. vCenter is added;
#         3. Hardware Islands are created;
#         4. "Onboard Local Cluster" (LC2S) catalog request is submitted.
#################################################################################################################
mandatory:
    Protected_avamar_grids:
        1-protected_site_fqdn:             &grid_b_fqdn            'london-ave01.vlab.local'
        2-protected_site_admin_username:   &ag_b_admin_user        'root'
        3-protected_site_admin_password:   &ag_b_admin_pwd         'Password123!'
        4-protected_site_soap_user:        &ag_b_soap_user         'root'
        5-protected_site_soap_password:    &ag_b_soap_pwd          'Emsee123_'
    Recovery_avamar_grids:
        1-recovery_site_fqdn:             &grid_d_fqdn            'london-ave01.vlab.local'
        2-recovery_site_admin_username:   &ag_d_admin_user        'root'
        3-recovery_site_admin_password:   &ag_d_admin_pwd         'Password123!'
        4-recovery_site_soap_user:        &ag_d_soap_user         'root'
        5-recovery_site_soap_password:    &ag_d_soap_pwd          'Emsee123_'
    Existing_sites:
        1-local_site1:           &site_a                 'SiteCork'
        2-local_site2:           &site_b                 'SiteLondon'
        3-remote_site1:          &site_c                 'SiteParis'
        4-remote_site2:          &site_d                 'SiteWarsaw'
    Existing_vCenters:
        1-protected_vCenter_name:             &vcs02_name             'vcs02'
        2-protected_vCenter_fqdn:             &vcs02_fqdn             'vcs02'
        3-protected_vCenter_datacenter:       &vcs02_dc               'London'
        1-recovery_vCenter_name:              &vcs04_name             'vcs04'
        2-recovery_vCenter_fqdn:              &vcs04_fqdn             'vcs04'
        3-recovery_vCenter_datacenter:        &vcs04_dc               'Warsaw'
    Existing_hardware_islands:
        1-local_HWI:            &hwi_a                  'RP4VM-LON-HWI-1'
        2-remote_HWI:           &hwi_b                  'RP4VM-WSW-HWI-2'
    Onboarded_cluster:
        1-protected_cluster:        &protected_cluster      'LON-WSW-RP-C2'
        2-recovery_cluster:         &recovery_cluster       'WSW-LON-RP-C2'
#################################################################################################################
optional_parameters:
    vRA:
        email:                &vra_email              admin@vlab.local
    avamar_grids:
        grid_4_protected_site:
            name:             &grid_b                 london-ave01
            changed_name:     &grid_b_edit            london-ave01-updated
        grid_4_recovery_site:
            name:             &grid_d                 warsaw-ave01
            changed_name:     &grid_d_edit            warsaw-ave01-updated
    backup_service_level:
        for_deploying_vm:
            name:             &busl_deploying_vm      busl-001
        for_setting_busl:
            name:             &busl_updating          busl-002
#################################################################################################################
added_sites:
  - *site_a
  - *site_c

added_vcenter:
  - *vcs02_name
  - *vcs04_name

added_hwi:
  - *hwi_a
  - *hwi_b

existed_clusters:
  - *protected_cluster
  - *recovery_cluster

#################################################################################################################
## For Debugging
#added_avamar_grid: [
#  *site_a,
#  *site_c
#]

#added_avamar_site_relationship:
# - asr_name:
#   backup_env_type:
#   sites: []

#  asr_name: ASR00014
#  backup_env_type: 2C2VC
#  sites: [*site_a, *site_b]

#added_avamar_replication_relationship: [
# ]

#added_backup_service_level:
#  backup_to_set_backup_service: *level_a
#  backup_to_operate_vm: ''
#  backup_to_set_backup_service: ''

#associated_avamar_proxy_cluster: []
#################################################################################################################
### Nodes for running workflow
onboard_cluster_type: LC2S

add_avamar_grid:
    - description: add avamar grid01
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_b
      avamar_grid_fqdn_name: *grid_b_fqdn
      admin_user_name: *ag_b_admin_user
      admin_password: *ag_b_admin_pwd
      soap_user_name: *ag_b_soap_user
      soap_password: *ag_b_soap_pwd
      request: unknown
      site_name: *site_a

    - description: add avamar grid02
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_d
      avamar_grid_fqdn_name: *grid_d_fqdn
      admin_user_name: *ag_d_admin_user
      admin_password: *ag_d_admin_pwd
      soap_user_name: *ag_d_soap_user
      soap_password: *ag_d_soap_pwd
      request: unknown
      site_name: *site_c

get_asr_from_vro:
    available_asr: []

edit_admin_full:
    - description: edit_admin_full avamar grid02
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: *grid_d_edit
      email_notification: Confirm
      admin_full: True

edit_avamar_grid:
    - description: update avamar grid01
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: *grid_d
      new_avamar_grid_name: *grid_d_edit
      edit_avamar_grid_fqdn_name: *grid_d_fqdn
      edit_admin_user_name: *ag_d_admin_user
      edit_admin_password: *ag_d_admin_pwd
      edit_soap_user_name: *ag_d_soap_user
      edit_soap_password: *ag_d_soap_pwd
      request: unknown
      edit_site_name: *site_a
      email_notification: Confirm

edit_avamar_site_relationship:
  site_first: *site_a
  site_second: *site_c
  site_third: ''

edit_avamar_replication_relationship:
    # Keep this key empty, it will fetch added arr
    arr:
    admin_full: Yes

add_avamar_site_relationship:
  is_RP4VM: True
  description: add avamar site relationship
  action: Add an ASR
  backup_env_type: MC2VC
  site_first: *site_a
  site_second: *site_c

add_an_avamar_replication_relationship:
  -
    allow_duplicated_arr: False
    description: add arr
    operation_type: Add Avamar Replication Relationship
    avamar_site_relationship_name:
    site1_avamar_grid: *grid_b
    site2_avamar_grid: *grid_d
    site3_avamar_grid:

get_arr_from_vro:
    available_arr: []

cluster_asr_to_associate:
    description: associate cluster to ASR
    reasons: testing
    cluster_action: Associate Cluster to ASR

add_backup_service_level:
    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *busl_deploying_vm
      'select_backup_schedule': 'Monthly'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'Until'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Daily'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *busl_updating
      'select_backup_schedule': 'Daily'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'For'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Monthly'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

display_backup_service_level:
    please_select_action_for_backup_service_level: Display Backup Service Levels
    email: Confirm

avamar_proxies_cluster_to_associate:
   -     avamar_proxies: []

run_admin_report:
  description: run admin report
  reasons: run reason
  select_a_backup_service_level_name: *busl_deploying_vm
  select_pdf_page_orientation: Portrait
  select_one_or_more_reports_to_run:
  select_a_time_frame: Last Day
  email_results: Yes
  email_address: *vra_email

delete_backup_service_level:
  - description: delete_backup_service_level_operate_vm
    reasons: reasons
    please_select_action_for_backup_service_level: Delete Backup Service Level
    select_backup_service_level_to_delete:
    confirm_deletion_of_backup_service_level: Yes

  - description: delete_backup_service_level_set_backup_service
    reasons: reasons
    please_select_action_for_backup_service_level: Delete Backup Service Level
    select_backup_service_level_to_delete:
    confirm_deletion_of_backup_service_level: Yes

delete_avamar_replication_relationship:
    description: delete arr
    operation_type: Delete Avamar Replication Relationship
    delete_arr: None

delete_avamar_site_relationship:
  description: delete avamar site relationship
  action: Delete an ASR

delete_avamar_grid:
    description: delete_avamar_grid
    select_operation_type: Delete Avamar Grid
    confirmation: Confirm