#################################################################################################################
# Caveats:
#     Preconditions:
#         1. Sites are created;
#         2. vCenters are added;
#         3. Hardware Islands are created;
#         4. "Onboard MP Cluster" (MP3S) catalog request is submitted.
#################################################################################################################
mandatory:
    Protected_local_avamar_grids:
       1-protected_avamar_fqdn:             &grid_a_fqdn            'cork-ave02.vlab.local'
       2-protected_avamar_admin_username:   &ag_a_admin_user        'root'
       3-protected_avamar_admin_password:   &ag_a_admin_pwd         'Password123!'
       4-protected_avamar_soap_user:        &ag_a_soap_user         'root'
       5-protected_avamar_soap_password:    &ag_a_soap_pwd          'Emsee123_'
    Protected_inter_avamar_grids:
       1-protected_inter_avamar_fqdn:             &grid_b_fqdn            'london-ave01.vlab.local'
       2-protected_inter_avamar_admin_username:   &ag_b_admin_user        'root'
       3-protected_inter_avamar_admin_password:   &ag_b_admin_pwd         'Password123!'
       4-protected_inter_avamar_soap_user:        &ag_b_soap_user         'root'
       5-protected_inter_avamar_soap_password:    &ag_b_soap_pwd          'Emsee123_'
    Recovery_avamar_grids:
       1-recovery_avamar_fqdn:             &grid_c_fqdn            'warsaw-ave01.vlab.local'
       2-recovery_avamar_admin_username:   &ag_c_admin_user        'root'
       3-recovery_avamar_admin_password:   &ag_c_admin_pwd         'Password123!'
       4-recovery_avamar_soap_user:        &ag_c_soap_user         'root'
       5-recovery_avamar_soap_password:    &ag_c_soap_pwd          'Emsee123_'
    Existing_sites:
        1-local_site:           &site_a                 'SiteCork'
        2-local_inter_site:     &site_b                 'SiteLondon'
        3-remote_site:          &site_c                 'SiteParis'
        4-site_D:               &site_d                 'SiteDublin'
        5-site_E:               &site_e                 'SiteShanghai'
    Existing_vCenters:
        1-protected_vCenter_name:                   &vcs01_name             'vcs01'
        2-protected_vCenter_fqdn:                   &vcs01_fqdn             'vcs01'
        3-protected_vCenter_datacenter:             &vcs01_dc               'Cork'
        4-protected_inter_vCenter_name:             &vcs02_name             'vcs02'
        5-protected_inter_vCenter_fqdn:             &vcs02_fqdn             'vcs02'
        6-protected_inter_vCenter_datacenter:       &vcs02_dc               'London'
        7-recovery_vCenter_name:                    &vcs03_name             'vcs03'
        8-recovery_vCenter_fqdn:                    &vcs03_fqdn             'vcs03'
        9-recovery_vCenter_datacenter:              &vcs03_dc               'Paris'
    Existing_hardware_islands:
        1-local_HWI:            &hwi_a                  'MP3S-CRK-HWI-1'
        2-inter_HWI:            &hwi_b                  'MP3S-LON-HWI-1'
        3-remote_HWI:           &hwi_c                  'MP3S-PAR-HWI-1'
    Onboarded_cluster:
        1-protected:        &protected_cluster      'CRK-LON-MP-C2'
        2-recovery:         &recovery_cluster       'PAR-MP-C2'
#################################################################################################################
optional_parameters:
    vRA:
        email:                &vra_email              admin@vlab.local
    avamar_grids:
        grid_4_protected_site:
            name:             &grid_a                 cork-ave01
            changed_name:     &grid_a_edit            cork-ave01-updated
        grid_4_protected_inter_site:
            name:             &grid_b                 london-ave01
            changed_name:     &grid_b_edit            london-ave01-updated
        grid_4_recovery_site:
            name:             &grid_c                 paris-ave01
            changed_name:     &grid_c_edit            paris-ave01-updated
    backup_servcie_level:
        name:                 &busl_name              backup-svc-E2E7-MP3S-DP
#################################################################################################################
added_sites:
  - *site_d
  - *site_e
  - *site_c

added_vcenter:
  - *vcs01_name
  - *vcs02_name
  - *vcs03_name

added_hwi:
  - *hwi_a
  - *hwi_b
  - *hwi_c

existed_clusters:
  - *protected_cluster
  - *recovery_cluster

#################################################################################################################
## For Debugging
added_avamar_grid:
#  - *grid_a
#  - *grid_a
#  - *grid_c

added_avamar_site_relationship:
# - asr_name: None
#   backup_env_type: None
#   sites: []

added_avamar_replication_relationship: [
]

added_backup_service_level:
  backup_to_operate_vm: ''
  backup_to_set_backup_service: ''

associated_avamar_proxy_cluster: []

#################################################################################################################
### Nodes for running workflow
onboard_cluster_type: MP3S

add_avamar_grid:
    - description: add avamar grid01
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_a
      avamar_grid_fqdn_name: *grid_a_fqdn
      admin_user_name: *ag_a_admin_user
      admin_password: *ag_a_admin_pwd
      soap_user_name: *ag_a_soap_user
      soap_password: *ag_a_soap_pwd
      request: unknown
      site_name: *site_a

    - description: add avamar grid02
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_b
      avamar_grid_fqdn_name: *grid_b_fqdn
      admin_user_name: *ag_b_admin_user
      admin_password: *ag_b_admin_pwd
      soap_user_name: *ag_b_soap_user
      soap_password: *ag_b_soap_pwd
      request: unknown
      site_name: *site_b

    - description: add avamar grid03
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *grid_c
      avamar_grid_fqdn_name: *grid_c_fqdn
      admin_user_name: *ag_c_admin_user
      admin_password: *ag_c_admin_pwd
      soap_user_name: *ag_c_soap_user
      soap_password: *ag_c_soap_pwd
      request: unknown
      site_name: *site_c

get_asr_from_vro:
    available_asr: []

edit_admin_full:
    - description: edit_admin_full avamar grid01
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: avamar_grid_A
      email_notification: Confirm
      admin_full: True

    - description: edit_admin_full avamar grid02
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: avamar_grid_B
      email_notification: Confirm
      admin_full: True

    - description: edit_admin_full avamar grid03
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: avamar_grid_C
      email_notification: Confirm
      admin_full: True

edit_avamar_grid:
    - description: update avamar grid01
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: *grid_a
      new_avamar_grid_name: avamar_grid_A
      edit_avamar_grid_fqdn_name: *grid_a_fqdn
      edit_admin_user_name: *ag_a_admin_user
      edit_admin_password: *ag_a_admin_pwd
      edit_soap_user_name: *ag_a_soap_user
      edit_soap_password: *ag_a_soap_pwd
      request: unknown
      edit_site_name: *site_a
      email_notification: Confirm

    - description: update avamar grid02
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: avamar_grid_B
      edit_avamar_grid_fqdn_name: *grid_b_fqdn
      edit_admin_user_name: *ag_b_admin_user
      edit_admin_password: *ag_b_admin_pwd
      edit_soap_user_name: *ag_b_soap_user
      edit_soap_password: *ag_b_soap_pwd
      request: unknown
      edit_site_name: *site_b
      email_notification: Confirm


    - description: update avamar grid03
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: paris-ave01
      new_avamar_grid_name: avamar_grid_C
      edit_avamar_grid_fqdn_name: *grid_c_fqdn
      edit_admin_user_name: *ag_c_admin_user
      edit_admin_password: *ag_c_admin_pwd
      edit_soap_user_name: *ag_c_soap_user
      edit_soap_password: *ag_c_soap_pwd
      request: unknown
      edit_site_name: *site_c
      email_notification: Confirm

edit_avamar_site_relationship:
  site_first: *site_a
  site_second: *site_b
  site_third: *site_c

edit_avamar_replication_relationship:
    # Keep this key empty, it will fetch added arr
    arr:
    admin_full: Yes

add_avamar_site_relationship:
  description: add avamar site relationship demo
  action: Add an ASR
  backup_env_type: 3C2VC
  site_first: *site_a
  site_second: *site_b
  site_third: *site_c

add_an_avamar_replication_relationship:
  -
    allow_duplicated_arr: False
    description: add arr
    operation_type: Add Avamar Replication Relationship
    avamar_site_relationship_name:
    site1_avamar_grid: *grid_a
    site2_avamar_grid: *grid_b
    site3_avamar_grid: *grid_c

get_arr_from_vro:
    available_arr: []

cluster_asr_to_associate:
    description: associate cluster to ASR
    reasons: testing
    cluster_action: Associate Cluster to ASR

associated_cluster_asr: []

add_backup_service_level:
    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *busl_name
      'select_backup_schedule': 'Monthly'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'Until'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Daily'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

display_backup_service_level:
    please_select_action_for_backup_service_level: Display Backup Service Levels
    email: Confirm

avamar_proxies_cluster_to_associate:
   - avamar_proxies: []
   - avamar_proxies: []

run_admin_report:
  description: run admin report
  reasons: run reason
  select_a_backup_service_level_name: *busl_name
  select_pdf_page_orientation: Portrait
  select_one_or_more_reports_to_run:
  select_a_time_frame: Last Day
  email_results: Yes
#  email_address: ehcDDadmin@emc.com
  email_address: *vra_email

delete_backup_service_level:
  - description: delete_backup_service_level_operate_vm
    reasons: reasons
    please_select_action_for_backup_service_level: Delete Backup Service Level
    select_backup_service_level_to_delete:
    confirm_deletion_of_backup_service_level: Yes

delete_avamar_replication_relationship:
    description: delete arr
    operation_type: Delete Avamar Replication Relationship
    delete_arr: None

delete_avamar_site_relationship:
  description: delete avamar site relationship demo
  action: Delete an ASR

delete_avamar_grid:
    description: delete_avamar_grid
    select_operation_type: Delete Avamar Grid
    confirmation: Confirm