# ################################ Configuration section #############################################################
# Automation user only needs to update the parameters in this section
# [Mandatory] parameters : you must update with the right ones in your environment.
# [Optional] parameters : you can suggested to update with your own, but not mandatory.

mandatory:
    Relationship_Mappings:
          relationship_mapping_1:
              1-mapping-a-cluster-name:              &mapping_a_cluster_name                 'CRK-HWI-1-C1'
              2-mapping-a-reservation-name:          &mapping_a_reservation_name             'Pair-LC1S-1'
              3-mapping-a-computer-resource:         &mapping_a_computer_resource            'CRK-HWI-1-C1 (VCS01)'
              4-mapping-a-network-path:              &mapping_a_np                           'VM Network'
              5-mapping-a-blueprint:                 &mapping_a_blueprint                    'Blueprint'
              6-mapping-a-vsphere-machine-id:        &mapping_a_vspmachine_id                'vSphere_Machine_1'
              7-mapping-a-reservation-policy-name:   &mapping_a_reservation_policy             'LC1S-RP4VM-RP1'
          relationship_mapping_2:
              1-mapping-b-cluster-name:              &mapping_b_cluster_name                 'PAR-HWI-1-C1'
              2-mapping-b-reservation-name:          &mapping_b_reservation_name             'Copy of Pair-LC1S-2'
              3-mapping-b-computer-resource:         &mapping_b_computer_resource            'PAR-HWI-1-C1 (VCS03)'
              4-mapping-b-network-path:              &mapping_b_np                           'VM Network'
              5-mapping-b-blueprint:                 &mapping_b_blueprint                    'Buleprint-dp'
              6-mapping-b-vsphere-machine-id:        &mapping_b_vspmachine_id                'vSphere_Machine_1'
              7-mapping-b-reservation-policy-name:   &mapping_b_reservation_policy             'LC1S-RP4VM-RP2'
    Site:
        site_name_protected:                 &site_name_protected                 'DR2S-DP-Site-Pro'
        site_name_recovery:                  &site_name_recovery                  'DR2S-DP-Site-Rec'
    vCenter:
        vcenter_name_protected:              &vcenter_name_protected              'DR2S-DP-vcs01'
        vcenter_name_recovery:               &vcenter_name_recovery               'DR2S-DP-vcs03'
    HWI:
        hwi_name_protected:                 &hwi_name_protected                   'DR2S-DP-HWI-1-Pro'
        hwi_name_recovery:                  &hwi_name_recovery                    'DR2S-DP-HWI-1-Rec'
    Avamar grid:
        1-protected_avamar_grid_fqdn:         &avamar_grid_fqdn_protected          'cork-ave02.vlab.local'
        2-recovery_avamar_grid_fqdn:          &avamar_grid_fqdn_recovery           'paris-ave02.vlab.local'
        3-admin_user_name:                    &admin_user_name                    'root'
        4-admin_password:                     &admin_password                     'Password123!'
        5-soap_user_name:                     &soap_user_name                     'root'
        6-soap_password:                      &soap_password                      'Emsee123_'
    provision_multiple_cloud_storage:
        1-storage_tier_a(Use comma to split the storage tiers):          &vipr_storage_tier_a        'CRK-Local-VP,CRK-Local-Unity-SAS-VP'
        2-storage_tier_b(Use comma to split the storage tiers):          &vipr_storage_tier_b        'PAR Local VP'
        3-storage_type:                 &storage_type               'VMFS'
        4-number_of_smaller_size_storages(Non-negative interger): &vPool_DS_Small  1
        5-number_of_larger_size_storages(Non-negative interger):  &vPool_DS_Large  0
    Backup Service Level:
        additional_email:                     &additional_email                   'louis.yin@emc.com'
    Deploy VM Parallel:
        cpu_count_max:                        &cpu_count_max              2
        ram_max:                              &ram_max                    8192
    Protected Avamar Proxy:
        1-protected_dns_updated:              &protected_dns_updated                'Yes'
        2-protected_datastore:                  &protected_avamar_proxy_datastore     'CRK-AVP-Templates01'
        3-protected_proxy_network:              &protected_proxy_network              'DPG_HPOD_L2X_1950(DVS_Cloud_VCS01_Cork)'
        4-protected_proxy_vm_name:              &protected_proxy_vm_name              'qe-avp09.vlab.local'
        5-protected_avamar_path:                &protected_avamar_path                '/clients/qe-avp09.vlab.local'
        6-protected_proxy_ip:                   &protected_proxy_ip                   '192.168.0.179'
        7-protected_proxy_netmask:              &protected_proxy_netmask              '255.255.248.0'
        8-protected_proxy_gateway:              &protected_proxy_gateway              '192.168.1.250'
        9-protected_dns_server_ip:              &protected_dns_server_ip              '192.168.1.10'
        11-protected_proxy_username:             &protected_proxy_username             'root'
        12-protected_proxy_password:             &protected_proxy_password             'avam@r'
        13-protected_avamar_domain:              &protected_avamar_domain              '/clients'
        14-protected_ova:                        &protected_avamar_proxy_ova           '/DPNInstalls/downloads/VMWARE_PROXY_SP3/AvamarCombinedProxy-linux-sles11_64-7.4.101-58.ova'
        15-protected_deployment_server:          &protected_deployment_server          '192.168.0.79'
        16-protected_deployment_server_username: &protected_deployment_server_username 'root'
        17-protected_deployment_server_password: &protected_deployment_server_password 'avam@r'
        18-protected_disable_verification:       &protected_disable_verification       'No'
    Recovery Avamar Proxy:
        1-recovery_dns_updated:              &recovery_dns_updated                'Yes'
        2-recovery_datastore:                  &recovery_avamar_proxy_datastore     'PAR-AVP-Templates01'
        3-recovery_proxy_network:              &recovery_proxy_network              'DPH_HPOD_L2X_1950'
        4-recovery_proxy_vm_name:              &recovery_proxy_vm_name              'qe-avp03.vlab.local'
        5-recovery_avamar_path:                &recovery_avamar_path                '/clients/qe-avp03.vlab.local'
        6-recovery_proxy_ip:                   &recovery_proxy_ip                   '192.168.0.173'
        7-recovery_proxy_netmask:              &recovery_proxy_netmask              '255.255.248.0'
        8-recovery_proxy_gateway:              &recovery_proxy_gateway              '192.168.1.250'
        9-recovery_dns_server_ip:              &recovery_dns_server_ip              '192.168.1.10'
        11-recovery_proxy_username:             &recovery_proxy_username             'root'
        12-recovery_proxy_password:             &recovery_proxy_password             'avam@r'
        13-recovery_avamar_domain:              &recovery_avamar_domain              '/clients'
        14-recovery_ova:                        &recovery_avamar_proxy_ova           '\\10.110.75.251\ehc_ai\software_repository_full\avamarve_ova\AVE-7.3.0.233.ova'
        15-recovery_deployment_server:          &recovery_deployment_server          '192.168.0.79'
        16-recovery_deployment_server_username: &recovery_deployment_server_username 'root'
        17-recovery_deployment_server_password: &recovery_deployment_server_password 'avam@r'
        18-recovery_disable_verification:       &recovery_disable_verification       'No'
optional:       
    Avamar Grid:
        avamar_name_protected:               &avamar_name_protected               'LC1S-RP4VM-ave01-1'
        avamar_name_recovery:                &avamar_name_recovery                'LC1S-RP4VM-ave01-2'
        new_avamar_grid_name_protected:      &new_avamar_grid_name_protected      'LC1S-RP4VM-ave01-1-new'
    backup_service_name_prefix:             &backup_name_prefix                    'E2E-1-LC1S-RP4VM'
################################# Configuration section #############################################################
    # no need to write------------
    added_sites: &added_sites []
    added_vcenter: &added_vcenter []
    # added vcentr relationship
    protected_vcenter: &protected_vcenter
    recovery_vcenter: &recovery_vcenter
    added_hwi: &added_hwi []
    existed_clusters: &existed_clusters [] #['CRK-HWI-1-C1', 'PAR-HWI-1-C1']
    added_avamar_grid: &added_avamar_grid [] #['LC1S-RP4VM-ave01-1', 'LC1S-RP4VM-ave01-2']
    # added asr
    asr_name: &asr_name #'ASR00008'
    backup_environment_type: &backup_environment_type #'MC2VC'
    sites: &sites [] #['DR2S-DP-Site-Pro', 'DR2S-DP-Site-Rec']
    added_avamar_replication_relationship: &added_avamar_replication_relationship []
    # paramters to added_backup_service_level
    backup_to_operate_vm: &backup_to_operate_vm
    backup_to_set_backup_service: &backup_to_set_backup_service
    # added cloud storage
    datastorage_name_1: &datastorage_name_1 [] #['CRK-Local-VP_1471588083333']
    storage_hwi_1: &storage_hwi_1
    storage_cluster_1: &storage_cluster_1
    srp_1: &srp_1
    datastorage_name_2: &datastorage_name_2 [] #['CRK-Local-VP_1471588083333']
    storage_hwi_2: &storage_hwi_2
    storage_cluster_2: &storage_cluster_2
    srp_2: &srp_2
    added_reservation_policy: &added_reservation_policy []
    assigned_buleprint: &assigned_buleprint []
    assigned_reservation: &assigned_reservation []
    deployed_vms: &deployed_vms []

onboard_cluster_type: LC2S

shared:
    current_browser:
        type:
        instance:
        launched: False
        current_user:
        is_login: False
    backup_service_levels:
        for_deletion: []
        for_deploy_vm:
        for_set_backup_service_level:

workflow_relation_mappings:
    Relation_Mapping_1:
         mapping_cluster_name:              *mapping_a_cluster_name
         mapping_reservation_name:          *mapping_a_reservation_name
         mapping_computer_resource:         *mapping_a_computer_resource
         mapping_network_path:              *mapping_a_np
         mapping_blueprint:                 *mapping_a_blueprint
         mapping_vsphere_machine_id:        *mapping_a_vspmachine_id
         mapping_reservation_policy_name:   *mapping_a_reservation_policy
    Relation_Mapping_2:
         mapping_cluster_name:              *mapping_b_cluster_name
         mapping_reservation_name:          *mapping_b_reservation_name
         mapping_computer_resource:         *mapping_b_computer_resource
         mapping_network_path:              *mapping_b_np
         mapping_blueprint:                 *mapping_b_blueprint
         mapping_vsphere_machine_id:        *mapping_b_vspmachine_id
         mapping_reservation_policy_name:   *mapping_b_reservation_policy

blueprints:
    - *mapping_a_blueprint
    - *mapping_b_blueprint

blueprint_machine_pairs:
    {*mapping_a_blueprint: *mapping_a_vspmachine_id,
    *mapping_b_blueprint: *mapping_b_vspmachine_id}

added_sites:
    - *site_name_protected
    - *site_name_recovery

added_vcenter_relationship:
  -
    {
    'protected_vcenter': *vcenter_name_protected,
    'recovery_vcenter': *vcenter_name_recovery
    }

added_vcenter:
    - *vcenter_name_protected
    - *vcenter_name_recovery

added_hwi:
    - *hwi_name_protected
    - *hwi_name_recovery

deploy_vm_parallel:
    with_dp: True
    description: ''
    number_of_vm: 1
    cpu_count_max: *cpu_count_max
    ram_max: *ram_max
    srm_power_on_priority: 3
    reason_for_request: test LC1S-RP4VM WF

cluster_maintenance:
  onboard_local_cluster_for_rp4vm:
    local_cluster_hardware_island: *hwi_name_protected
    local_cluster_name: *mapping_a_cluster_name
    partner_cluster_hardware_island: *hwi_name_recovery
    partner_cluster_name: *mapping_b_cluster_name

add_avamar_grid:
    - description: *avamar_name_protected
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *avamar_name_protected
      avamar_grid_fqdn_name: *avamar_grid_fqdn_protected
      admin_user_name: *admin_user_name
      admin_password: *admin_password
      soap_user_name: *soap_user_name
      soap_password: *soap_password
      request: unknown
      site_name: *site_name_protected

    - description: *avamar_name_recovery
      select_operation_type: Add Avamar Grid
      avamar_grid_name: *avamar_name_recovery
      avamar_grid_fqdn_name: *avamar_grid_fqdn_recovery
      admin_user_name: *admin_user_name
      admin_password: *admin_password
      soap_user_name: *soap_user_name
      soap_password: *soap_password
      request: unknown
      site_name: *site_name_recovery

add_avamar_proxy:
    - dns_updated: *protected_dns_updated
      tenant_cluster: *mapping_a_cluster_name
      datastore: *protected_avamar_proxy_datastore
      proxy_network: *protected_proxy_network
      proxy_vm_name: *protected_proxy_vm_name
      avamar_path: *protected_avamar_path
      proxy_ip: *protected_proxy_ip
      proxy_netmask: *protected_proxy_netmask
      proxy_gateway: *protected_proxy_gateway
      dns_server_ip: *protected_dns_server_ip
      proxy_username: *protected_proxy_username
      proxy_password: *protected_proxy_password
      avamar_grid: *avamar_name_protected
      avamar_domain: *protected_avamar_domain
      ova: *protected_avamar_proxy_ova
      deployment_server: *protected_deployment_server
      deployment_server_username: *protected_deployment_server_username
      deployment_server_password: *protected_deployment_server_password
      disable_verification: *protected_disable_verification

    - dns_updated: *recovery_dns_updated
      tenant_cluster: *mapping_b_cluster_name
      datastore: *recovery_avamar_proxy_datastore
      proxy_network: *recovery_proxy_network
      proxy_vm_name: *recovery_proxy_vm_name
      avamar_path: *recovery_avamar_path
      proxy_ip: *recovery_proxy_ip
      proxy_netmask: *recovery_proxy_netmask
      proxy_gateway: *recovery_proxy_gateway
      dns_server_ip: *recovery_dns_server_ip
      proxy_username: *recovery_proxy_username
      proxy_password: *recovery_proxy_password
      avamar_grid: *avamar_name_recovery
      avamar_domain: *recovery_avamar_domain
      ova: *recovery_avamar_proxy_ova
      deployment_server: *recovery_deployment_server
      deployment_server_username: *recovery_deployment_server_username
      deployment_server_password: *recovery_deployment_server_password
      disable_verification: *recovery_disable_verification

add_avamar_site_relationship:
  backup_env_type: MC2VC
  site_first: *site_name_protected
  site_second: *site_name_recovery
  site_third:

add_an_avamar_replication_relationship:
  -
    allow_duplicated_arr: False
    description: 'add arr'
    operation_type: 'Add Avamar Replication Relationship'
    avamar_site_relationship_name:
    site1_avamar_grid:
    site2_avamar_grid:
    site3_avamar_grid:

edit_avamar_replication_relationship:
    'arr':
    'admin_full': True

cluster_asr_to_associate:
    description: associate cluster to ASR
    reasons: testing
    cluster_action: Associate Cluster to ASR

associated_cluster_asr:
    {}

avamar_proxies_cluster_to_associate:
  - avamar_proxies: []
  - avamar_proxies: []

add_backup_service_level:
    - 'description': 'add backup service level'
      'reasons': 'reasons'
      'please_select_action_for_backup_service_level': 'Add Backup Service Level'
      'specify_the_service_level_name': *backup_name_prefix
      'select_backup_schedule': 'Monthly'
      'schedule_start_time': '18:00'
      'schedule_week_number': 'First'
      'schedule_weekday': 'Sunday'
      'regular_retention_policy': 'Until'
      'retention_for_number': '3'
      'retention_unit': 'Weeks'
      'retention_date': '7/22/17'
      'retention_time': '10:03 PM'
      'long_term_retention_policy': '2'
      'replication_schedule_type': 'Daily'
      'replication_weekday': 'Monday'
      'replication_week_number': 'First'
      'replication_start_time': '20:00'

provision_multiple_cloud_storage:
    -
      'cluster': *mapping_a_cluster_name
      'hwi_name': *hwi_name_protected
      'virtual_pools': *vipr_storage_tier_a
      'storage_type': *storage_type
      'vPool_DS_Small': *vPool_DS_Small
      'vPool_DS_Large': *vPool_DS_Large
    -
      'cluster': *mapping_b_cluster_name
      'hwi_name': *hwi_name_recovery
      'virtual_pools': *vipr_storage_tier_b
      'storage_type': *storage_type
      'vPool_DS_Small': *vPool_DS_Small
      'vPool_DS_Large': *vPool_DS_Large


assign_reservation_policy_to_blueprint:
    blueprint_names: []
    reservation_policy_name:

set_backup_service_level:
    backup_service_level_name:

delete_datastore:
    - description: Delete Logic
      reasons: del logic

delete_avamar_replication_relationship:
    'description': 'delete arr'
    'operation_type': 'Delete Avamar Replication Relationship'
    'delete_arr':

delete_hwi:
    del_reasons: del
    del_description: del hwi
    del_performed_active: Delete Hardware Island
    isdel_obj: Confirm

delete_vcenter:
    description: delete vcenter
    reasons: test
    select_operation: Delete vCenter
    ensure_delete_info: Confirm

delete_avamar_site_relationship:
  description: delete avamar site relationship demo
  action: Delete an ASR
  avamar_site_relationship_name:

edit_avamar_grid:
    - description: update avamargrid01
      select_operation_type: Edit Avamar Grid Details
      avamar_grid_name: *avamar_name_protected
      new_avamar_grid_name: *new_avamar_grid_name_protected
      edit_avamar_grid_fqdn_name: *avamar_grid_fqdn_protected
      edit_admin_user_name: *admin_user_name
      edit_admin_password: *admin_password
      edit_soap_user_name: *soap_user_name
      edit_soap_password: *soap_password
      edit_site_name: *site_name_protected
      request: unknown
      email_notification: Confirm

edit_admin_full:
    - description: update avamargrid01
      select_operation_type: Edit Avamar Grid Admin Full
      avamar_grid_name: *new_avamar_grid_name_protected
      email_notification: Confirm
      admin_full: True

delete_avamar_grid:
    description: delete_avamar_grid
    select_operation_type: Delete Avamar Grid
    confirmation: Confirm

existed_clusters:
    *existed_clusters

added_avamar_grid:
    *added_avamar_grid

added_avamar_site_relationship:
   - asr_name: *asr_name
     backup_env_type: *backup_environment_type
     sites: *sites

added_avamar_replication_relationship:
    *added_avamar_replication_relationship

added_backup_service_level:
    {
       'backup_to_operate_vm': *backup_to_operate_vm,
       'backup_to_set_backup_service': *backup_to_set_backup_service
    }

added_cloud_storage:
   - hwi_name: *storage_hwi_1
     cluster_name: *storage_cluster_1
     name: *datastorage_name_1
     srp: *srp_1
   - hwi_name: *storage_hwi_2
     cluster_name: *storage_cluster_2
     name: *datastorage_name_2
     srp: *srp_2

deployed_vms: *deployed_vms

added_reservation_policy:
    *added_reservation_policy

assigned_reservation_policy_reservations: *assigned_reservation

assigned_reservation_policy_blueprints: [*mapping_a_reservation_policy, *mapping_b_reservation_policy]